services:
  database:
    image: mysql
    container_name: my-symfony-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-symfony-app-phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:80
    networks:
      - symfony

networks:
  symfony: